name: Debug form
description: that works
body:
  - type: dropdown
    id: branch
    attributes:
      label: Branch
      description: Select the branch to run the benchmark on
      options:
        - main
        - staging
      default: main
    validations:
      required: true
