name: Test form
description: Select a branch
title: Select a branch
body:
  - type: dropdown
    id: branch
    attributes:
      label: Branch
      description: Select the branch to run the benchmark on
      options:
        - main
        - staging
      default: 0
    validations:
      required: true
