name: form
description: test form
title: Run form
body:
  - type: dropdown
    id: branch
    attributes:
      label: Branch
      description: Select the branch
      options:
        - main
        - staging
      default: main
    validations:
      required: true

  - type: checkboxes
    id: option2
    attributes:
      label: Letter
      description: Select the letter(s)
      options:
        - label: A
        - label: B
        - label: C
    validations:
      required: true
